version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/config/requirements"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "coverage*"
      conflict-dependencies:
        patterns:
          - "numpy*"
      prod-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"
