version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/service/config/requirements"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/web"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "monthly"