name: release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Find version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Decrypt environment file
        run: ./scripts/decrypt_env.sh
        env:
          ENV_DECODE_SECRET: ${{ secrets.ENV_DECODE_SECRET }}
      - name: Build images
        run: docker-compose build
      - name: Save images
        run: |
          mkdir -p docker
          docker save -o docker/r4l-web r4l/web
          docker save -o docker/r4l-service r4l/service
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_VERSION }}
          tag: ${{ github.ref }}
          bodyFile: CHANGELOG.md
          artifacts: "docker-compose.yml,environment.gpg,docker/r4l-web,docker/r4l-service,scripts/launch.sh"